/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root';
import { Route as ClipboardAnalyzerImport } from './routes/clipboard-analyzer';
import { Route as ClipboardImport } from './routes/clipboard';
import { Route as IndexImport } from './routes/index';

// Create/Update Routes

const ClipboardAnalyzerRoute = ClipboardAnalyzerImport.update({
  id: '/clipboard-analyzer',
  path: '/clipboard-analyzer',
  getParentRoute: () => rootRoute,
} as any);

const ClipboardRoute = ClipboardImport.update({
  id: '/clipboard',
  path: '/clipboard',
  getParentRoute: () => rootRoute,
} as any);

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    '/clipboard': {
      id: '/clipboard';
      path: '/clipboard';
      fullPath: '/clipboard';
      preLoaderRoute: typeof ClipboardImport;
      parentRoute: typeof rootRoute;
    };
    '/clipboard-analyzer': {
      id: '/clipboard-analyzer';
      path: '/clipboard-analyzer';
      fullPath: '/clipboard-analyzer';
      preLoaderRoute: typeof ClipboardAnalyzerImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/clipboard': typeof ClipboardRoute;
  '/clipboard-analyzer': typeof ClipboardAnalyzerRoute;
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/clipboard': typeof ClipboardRoute;
  '/clipboard-analyzer': typeof ClipboardAnalyzerRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  '/': typeof IndexRoute;
  '/clipboard': typeof ClipboardRoute;
  '/clipboard-analyzer': typeof ClipboardAnalyzerRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: '/' | '/clipboard' | '/clipboard-analyzer';
  fileRoutesByTo: FileRoutesByTo;
  to: '/' | '/clipboard' | '/clipboard-analyzer';
  id: '__root__' | '/' | '/clipboard' | '/clipboard-analyzer';
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  ClipboardRoute: typeof ClipboardRoute;
  ClipboardAnalyzerRoute: typeof ClipboardAnalyzerRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClipboardRoute: ClipboardRoute,
  ClipboardAnalyzerRoute: ClipboardAnalyzerRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/clipboard",
        "/clipboard-analyzer"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/clipboard": {
      "filePath": "clipboard.tsx"
    },
    "/clipboard-analyzer": {
      "filePath": "clipboard-analyzer.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
